import Head from 'next/head'
import Link from 'next/link'

export default function HomePage() {
  
  return (
    <div className='w-full'>
      <Head>
        <title>Simple Store</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main >
      <div className="hero  ">
        <div className="hero-content text-center w-full">
          <div className="w-full">
            <h1 className="text-5xl font-bold">Welcome to Simple Store</h1>
            <p className="py-6">Simple e-commerce store with notifications and PayPal's Payment.</p>
            <p className="font-bold">Technical features:</p>
            <ul className='mb-5'>
              <li>Shopping Cart</li>
              <li>Pagination</li>
              <li>Responsive Design</li>
              <li>Notifications</li>
              <li>Tailwind and Daisy UI</li>
              <li>Next JS</li>
              <li>Typescript</li>
            </ul>
            <Link href='/products' className="btn btn-primary">Start to buy!</Link>
          </div>
        </div>
      </div>
      </main>
    </div>
  )
}

