import Head from 'next/head'
import {
  PayPalScriptProvider,
  PayPalButtons,
} from '@paypal/react-paypal-js'

import useOrders from '../components/orders/useOrders'

export default function HomePage() {

  return (
    <div >
      <Head>
        <title>App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main >
        
      </main>
    </div>
  )
}

