import Head from 'next/head'
import {
  PayPalScriptProvider,
  PayPalButtons,
} from '@paypal/react-paypal-js'

import useOrders from '../components/orders/useOrders'

export default function Home() {
  const { createPayPalOrder, onApprove, options, fundingSource } = useOrders()

  return (
    <div >
      <Head>
        <title>App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main >
        <PayPalScriptProvider
          options={options}
        >
          <PayPalButtons
            style={{
              color: 'gold',
              shape: 'rect',
              label: 'pay',
              height: 50,
            }}
            fundingSource={fundingSource}
            createOrder={createPayPalOrder}
            onApprove={onApprove}
          />
        </PayPalScriptProvider>
      </main>
    </div>
  )
}

